# Generated by Django 5.0.3 on 2024-04-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eudrfarmmodel',
            name='farm_district',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='ADMIN', max_length=255),
        ),
    ]
