# Generated by Django 5.0.6 on 2024-06-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0011_eudruploadedfilesmodel_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eudrfarmmodel',
            name='remote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='ADMIN', max_length=255),
        ),
    ]
