# Generated by Django 5.0.6 on 2024-07-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0013_remove_eudrfarmmodel_is_eudr_compliant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eudrfarmmodel',
            name='geoid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='ADMIN', max_length=255),
        ),
    ]
