# Generated by Django 5.0.6 on 2024-07-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0017_alter_eudrusermodel_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhispAPISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_size', models.PositiveIntegerField(default=500, help_text='Size of WHISP API data chunks to fetch.')),
            ],
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='ADMIN', max_length=255),
        ),
    ]
