# Generated by Django 5.0.6 on 2024-08-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0022_eudrcollectionsitemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eudrcollectionsitemodel',
            name='site_manager',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='ADMIN', max_length=255),
        ),
    ]
