# Generated by Django 5.0.6 on 2024-08-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0024_eudrfarmmodel_member_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EUDRUploadedFilesModel',
        ),
        migrations.RemoveField(
            model_name='eudrfarmmodel',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='eudrfarmmodel',
            name='collection_site',
        ),
        migrations.RemoveField(
            model_name='eudrfarmmodel',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='eudrfarmmodel',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='eudrcollectionsitemodel',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eudrcollectionsitemodel',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eudrcollectionsitemodel',
            name='site_district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eudrcollectionsitemodel',
            name='site_village',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='ADMIN', max_length=255),
        ),
    ]
