# Generated by Django 5.0.6 on 2024-08-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0025_delete_eudruploadedfilesmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EUDRUploadedFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eudrcollectionsitemodel',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='eudrcollectionsitemodel',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='eudrfarmmodel',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eudrfarmmodel',
            name='collection_site',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eudrfarmmodel',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eudrfarmmodel',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eudrcollectionsitemodel',
            name='site_district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eudrcollectionsitemodel',
            name='site_village',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='ADMIN', max_length=255),
        ),
    ]
