# Generated by Django 5.0.6 on 2024-09-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0027_remove_eudrfarmmodel_site_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eudrcollectionsitemodel',
            old_name='site_manager',
            new_name='agent_name',
        ),
        migrations.RenameField(
            model_name='eudrcollectionsitemodel',
            old_name='site_district',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='eudrcollectionsitemodel',
            old_name='site_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='eudrcollectionsitemodel',
            old_name='site_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='eudrcollectionsitemodel',
            old_name='site_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='eudrcollectionsitemodel',
            old_name='site_village',
            new_name='village',
        ),
        migrations.RemoveField(
            model_name='eudruploadedfilesmodel',
            name='device_id',
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='ADMIN', max_length=255),
        ),
    ]
