# Generated by Django 5.0.6 on 2024-09-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0028_rename_site_manager_eudrcollectionsitemodel_agent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='ADMIN', max_length=255),
        ),
    ]
