# Generated by Django 5.0.6 on 2024-09-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0029_alter_eudrusermodel_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eudrcollectionsitemodel',
            name='device_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='ADMIN', max_length=255),
        ),
    ]
