# Generated by Django 5.0.6 on 2024-09-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0038_alter_eudrusermodel_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eudrusermodel',
            old_name='email',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='AGENT', max_length=255),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
