# Generated by Django 5.0.6 on 2024-09-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0039_rename_email_eudrusermodel_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eudruploadedfilesmodel',
            name='s3_file_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='AGENT', max_length=255),
        ),
    ]
