# Generated by Django 5.0.6 on 2024-09-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0040_eudruploadedfilesmodel_s3_file_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eudruploadedfilesmodel',
            name='s3_file_id',
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='AGENT', max_length=255),
        ),
    ]
