# Generated by Django 5.0.6 on 2024-10-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0042_eudrfarmbackupmodel_accuracies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eudrfarmbackupmodel',
            name='accuracies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='eudrfarmmodel',
            name='accuracies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='AGENT', max_length=255),
        ),
    ]
