# Generated by Django 5.0.6 on 2024-10-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0043_alter_eudrfarmbackupmodel_accuracies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eudrfarmmodel',
            name='polygon_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eudrusermodel',
            name='user_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='AGENT', max_length=255),
        ),
    ]
