# Generated by Django 5.1.3 on 2024-11-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eudr_backend', '0051_alter_eudrusermodel_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EUDRUserModel',
        ),
    ]
